#!/usr/bin/env bash

PACKAGE_NAME=docker-ros
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BUILD_DIR=$(mktemp -d)
DEB_PACKAGE_DIR=${BUILD_DIR}/${PACKAGE_NAME}
DEB_PACKAGE=${SCRIPT_DIR}/${PACKAGE_NAME}.deb

# create a base directory
mkdir -p ${DEB_PACKAGE_DIR}

# place the exectuable
mkdir -p ${DEB_PACKAGE_DIR}/usr/local/bin/
cp ${SCRIPT_DIR}/docker-ros ${DEB_PACKAGE_DIR}/usr/local/bin/

# place the runtime files
mkdir -p ${DEB_PACKAGE_DIR}/usr/local/share/docker_ros
cp ${SCRIPT_DIR}/get_completions ${DEB_PACKAGE_DIR}/usr/local/share/docker_ros/

# place the bash completion script to appropriate location
mkdir -p ${DEB_PACKAGE_DIR}/etc/bash_completion.d/
cp ${SCRIPT_DIR}/docker-ros-bash-completion ${DEB_PACKAGE_DIR}/etc/bash_completion.d/

mkdir -p ${DEB_PACKAGE_DIR}/DEBIAN

# configure the control file
echo -e "Package: ${PACKAGE_NAME}" > ${DEB_PACKAGE_DIR}/DEBIAN/control
echo -e "Version: 0.0" >> ${DEB_PACKAGE_DIR}/DEBIAN/control
echo -e "Depends: docker-ce, bash-completion" >> ${DEB_PACKAGE_DIR}/DEBIAN/control
echo -e "Section: custom" >> ${DEB_PACKAGE_DIR}/DEBIAN/control
echo -e "Priority: optional" >> ${DEB_PACKAGE_DIR}/DEBIAN/control
echo -e "Architecture: all" >> ${DEB_PACKAGE_DIR}/DEBIAN/control
echo -e "Maintainer: Abhijit Majumdar" >> ${DEB_PACKAGE_DIR}/DEBIAN/control
echo -e "Description: ROS over docker" >> ${DEB_PACKAGE_DIR}/DEBIAN/control

# The post install script
echo '#!/bin/bash' > ${DEB_PACKAGE_DIR}/DEBIAN/postinst
echo 'su `logname` -c "/usr/local/bin/docker-ros --start"' >> ${DEB_PACKAGE_DIR}/DEBIAN/postinst
chmod +x ${DEB_PACKAGE_DIR}/DEBIAN/postinst

# The pre uninstall script
echo '#!/bin/bash' > ${DEB_PACKAGE_DIR}/DEBIAN/prerm
echo 'su `logname` -c "/usr/local/bin/docker-ros --clear"' >> ${DEB_PACKAGE_DIR}/DEBIAN/prerm
chmod +x ${DEB_PACKAGE_DIR}/DEBIAN/prerm

# build deb
dpkg-deb --build ${DEB_PACKAGE_DIR} ${DEB_PACKAGE}

# clean build cache
rm -rf ${BUILD_DIR}