#!/usr/bin/env bash

_docker_ros_completions(){
    COMPREPLY=()
    if [ "${#COMP_WORDS[@]}" -gt "1" ]; then
        if [ "${COMP_WORDS[1]}" == '' ] || [ "${COMP_WORDS[1]:0:1}" == '-' ]; then
            COMPREPLY=($(compgen -W "<COMMAND> --start --stop --add --clear --distro --help" -- "${COMP_WORDS[-1]}"))
        else
            # test to see if this is the first time running docker-ros
            if [ "$(docker-ros --check)" == "true" ]; then
                local suggestions="$(docker-ros get_completions \'${COMP_WORDS[@]:1}\' | sed 's/\r//g' | sed 's|\"|\\\"|g' | sed -z 's|\n| |g')"
                if [[ "$suggestions" == *"\""*"\""* ]]; then
                    COMPREPLY=("$(printf '%s' "$suggestions")")
                elif [ "${COMP_LINE[@]: -1}" == ' ' ]; then
                    COMPREPLY=($(compgen -W "$suggestions" -- ""))
                else
                    COMPREPLY=($(compgen -W "$suggestions" -- ${COMP_WORDS[-1]}))
                fi
            else
                echo "Command completion will not work because this is the first time running docker-ros! Run 'docker-ros start' first and try again"
            fi
        fi
    fi
}

complete -F _docker_ros_completions docker-ros