#!/usr/bin/env bash

_docker_ros_completions(){
    COMPREPLY=()
    if [ "${#COMP_WORDS[@]}" -gt "1" ]; then
        local suggestions
        if [ "${COMP_WORDS[1]}" == '' ]; then
            COMPREPLY=($(compgen -W "<COMMAND> start stop add clear distro" -- ""))
        else
            suggestions="$(docker-ros get_completions \'${COMP_WORDS[@]:1}\' | sed 's/\r//g' | xargs)"
            if [ "${COMP_LINE[@]: -1}" == ' ' ]; then
                COMPREPLY=($(compgen -W "$suggestions" -- ""))
            else
                COMPREPLY=($(compgen -W "$suggestions" -- ${COMP_WORDS[-1]}))
            fi
        fi
    fi
}

complete -F _docker_ros_completions docker-ros